# Generated by Django 4.0.5 on 2022-06-24 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guess',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('puzzle', models.IntegerField(default=0, null=True)),
                ('studentId', models.IntegerField(default=0, null=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('guess', models.CharField(max_length=100, null=True)),
                ('correct', models.BooleanField(default=False)),
                ('submitTime', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'Guess',
            },
        ),
    ]
