# Generated by Django 4.0.5 on 2022-06-24 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MDSCApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guess',
            name='points',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
