# Generated by Django 4.0.5 on 2022-06-26 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MDSCApp', '0002_guess_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('msgTime', models.DateTimeField(null=True)),
                ('msg', models.TextField(max_length=10000, null=True)),
            ],
            options={
                'db_table': 'Announcement',
            },
        ),
    ]
